"""empty message

Revision ID: fc5af07f66f
Revises: 492f7f20507f
Create Date: 2015-06-23 15:39:20.829657

"""

# revision identifiers, used by Alembic.
revision = 'fc5af07f66f'
down_revision = '492f7f20507f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_blogpost', sa.Column('slug', sa.String(length=255), nullable=False, default='', server_default=''))
    #op.create_unique_constraint(None, 'blog_blogpost', ['slug'])
    ### end Alembic commands ###
    pass


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog_blogpost', type_='unique')
    op.drop_column('blog_blogpost', 'slug')
    ### end Alembic commands ###
